{
 "title": "gnmic",
 "time": { "from": "2024-03-26T14:49:33.685Z", "to": "2024-03-26T15:45:40.917Z" },
 "templating": {
  "list": [
   {
    "name": "source",
    "query": {
     "query": "label_values(interfaces_interface_state_counters_in_pkts, source)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "broadcastpackets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "interfaces_interface_state_counters_in_broadcast_pkts{source=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out_octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "interfaces_interface_state_counters_out_octets{source=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In_unicast_pkts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "interfaces_interface_state_counters_in_unicast_pkts{source=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP_AS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instances_network_instance_protocols_protocol_bgp_global_config_as{source=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eos_native_Kernel_proc_meminfo_active{source=\"$source\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}