# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'gnmic'
    scrape_interval: 10s
    consul_sd_configs:
      - server: clab-cluster-consul-agent:8500
  - job_name: 'clab-cluster-gnmic1'
    static_configs:
      - targets: ['clab-cluster-gnmic1:9804']

  - job_name: 'clab-cluster-gnmic2'
    static_configs:
      - targets: ['clab-cluster-gnmic2:9804']

  - job_name: 'clab-cluster-gnmic3'
    static_configs:
      - targets: ['clab-cluster-gnmic3:9804']
